name: generate contribution snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: randrada-usa
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2310B981&color_dots=%232d3343,%234b5563,%237C3AED,%23A78BFA,%2322D3EE
            dist/github-contribution-grid-snake-light.svg?color_snake=%230891B2&color_dots=%23ebedf0,%23a5b4fc,%23818cf8,%236366f1,%230891B2

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
